travis:
  secure:
    BINSTAR_TOKEN: j33SkZLC6WSywf73LAyBOu5eDYvNVSs9VghTre27ogXE1ZBiSFfBFodovpwEGGpdI0kjSdFR5GiOzSGp8bfTmj4m6D4cIE8g5iYyHwmk3eN7jlRjcFlMpQfmGtRksbp9C5gB+hlD2CeqB15Y+eMYyx/WLLDyNdi/npsCq9W5/WWNL0GaOuiQgvygNbqEA2ey2E3JeQ1uCWZbMzTyCPEMDp4QdMzi6H7K6qIdjNXYzS6kWjWHOuoReLfLPB3GsHdCPltHYLodS/MVJgL6ECyf/eDe27DZSTBqbRh4bwhC/YNfMcKSoxoFb7Cptp4jKwwzf2IwQRW19/OySxdO4WotrUQxhH+DPlK6PpO5Ul1ZxsmEoe2o6rQOvMInqqOM+dg4B9QUkfKTTJDPqx3OOmj0XaetBZOfXyaGx33MgHxaglFpf9YrBm4DWOx0tccTxbtvx6xwVhqXkD+qptWPH9aJoegD0HEgH67xKn8xer/XAwZBZ4MI2HyqNWwlCOtrXV9X8KBm7buGetDbce8ZpnpGI5kbbc+GcUoDdb9snOX9wMcLyRugMNMY1w7XpcXgAb03UGxkrD88zR9PmotB2UAXNqTQwPRsPkSXT99Uvvw0A0HcLHlMjNxibtTs9qZo0abI0u596PuIpO9XquC85+9OysOrkK7kXDBl9iKisA9tJMM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
